### ISSUE TITLE
Melhorar legibilidade

### ISSUE THREAD

**Issue by felipesabino** [felipesabino/bomdianao#2]
Arrumar o CSS para melhorar legibilidade 

- padronizar a fonte
- melhorar cores (está bem monocromático e sem graça)
- corrigir estilo dos links

**Comment by Ocramoi** [comment]
Posso implementar essas mudanças caso ainda seja necessário!

**Comment by felipesabino** [comment]
Opa, fala @Ocramoi , se puder fazer ficarei muito grato sim!

**Comment by Ocramoi** [comment]
> 
> 
> Opa, fala @Ocramoi , se puder fazer ficarei muito grato sim!

Já mando a pull request!

**Comment by Ocramoi** [comment]
PR mandada!

**Comment by felipesabino** [comment]
Closed by #4
