### ISSUE TITLE
Corrigir estilo mobile

### ISSUE THREAD

**Issue by felipesabino** [felipesabino/bomdianao#3]
Arrumar fonte

- tamanho do texto nos exemplos de chat ficam minúsculos
- texto do rodapé é ilegível
- adicionar espaçamento entre parágrafos

![Screen Shot 2020-10-01 at 4 35 16 PM](https://user-images.githubusercontent.com/700480/94854973-29a52080-0404-11eb-871c-685c40d35e53.png)

**Comment by askmon** [comment]
Quais as dimensões ou device que vc fez o teste? Eu consigo reproduzir o rodapé, mas o texto das mensagens fica normal pra mim:
![image](https://user-images.githubusercontent.com/711732/95108305-7bee8600-0711-11eb-8756-b089d1a46cb0.png)

**Comment by felipesabino** [comment]
Hmmm essa issue foi criada antes do PR #4 , lá teve bastante melhoria de estilo mesmo e esse problema do texto das mensagens e do espaçamento dos parágrafos parece que foram mitigados mesmo 😎
