### ISSUE TITLE
Implementar conteúdo de compartilhamento

### ISSUE THREAD

**Issue by felipesabino** [felipesabino/bomdianao#5]
Atualmente ao compartilhar https://bomdianao.com.br é mostrado apenas o título análogo ao domínio do site como informação

![Screenshot_20201001-211032.png](https://user-images.githubusercontent.com/700480/94875634-b44d4600-042b-11eb-9ae1-f10b0e4db066.png)

Mas deveria conter também como descrição o que atualmente é o título do conteúdo da página

> Por favor não diga apenas "bom dia" no chat

Como acontece com https://nohello.com

![Screenshot_20201001-211545.png](https://user-images.githubusercontent.com/700480/94875718-fd9d9580-042b-11eb-809b-d9f66b9f9284.png)

**Comment by vczoika** [comment]
Olá, tudo bem? Fiz um pull request que pode ser que tenha resolvido o seu problema.
